version: '3.9'

services:
  db:
    image: postgres:16.2
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/etl:/docker-entrypoint-initdb.d
    env_file:
      - .env
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U app -d movies_database' ]
      interval: 10s
      timeout: 5s
      retries: 5

  etl:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:9200 || exit 1",
        ]
      interval: 1s
      timeout: 5s
      retries: 20

volumes:
  postgres-data:
  elasticsearch-data: